[package]
name = "tcp"
version = "0.1.0"
edition = "2024"

[lib]
name = "tcp"

[[bin]]
name = "tcp"

[dependencies]
bitflags = "2.9.0"
etherparse = "0.17"
nix = { version = "0.29.0", features = ["poll"] }
tun = "0.7"